"""Import the small CC0 Kenney models into MuJoCo's Z-up coordinate system."""
from __future__ import annotations
import argparse
import io
import json
from pathlib import Path
from urllib.request import urlopen
from zipfile import ZipFile

SOURCE = 'https://kenney.nl/media/pages/assets/city-kit-commercial/a742d900eb-1753115042/kenney_city-kit-commercial_2.1.zip'
MODELS = ('building-a', 'building-b', 'building-c', 'building-f', 'building-i',
          'building-j', 'building-l', 'building-n', 'building-skyscraper-a',
          'building-skyscraper-b', 'building-skyscraper-d', 'building-skyscraper-e')


def prepare(archive=None):
    root = Path(__file__).with_name('urban_assets')
    root.mkdir(exist_ok=True)
    payload = Path(archive).read_bytes() if archive else urlopen(SOURCE, timeout=60).read()
    manifest = {}
    with ZipFile(io.BytesIO(payload)) as z:
        for name in MODELS:
            source = z.read('Models/OBJ format/'+name+'.obj').decode()
            vertices = [list(map(float, l.split()[1:4])) for l in source.splitlines() if l.startswith('v ')]
            bounds = [(min(v[a] for v in vertices), max(v[a] for v in vertices)) for a in range(3)]
            cx = sum(bounds[0])/2
            cz = sum(bounds[2])/2
            out = ['# CC0 Kenney City Kit Commercial 2.1; converted Y-up to Z-up']
            for line in source.splitlines():
                parts = line.split()
                if not parts:
                    continue
                if parts[0] == 'v':
                    x, y, zz = map(float, parts[1:4])
                    out.append(f'v {x-cx:.7f} {-(zz-cz):.7f} {y-bounds[1][0]:.7f}')
                elif parts[0] == 'vn':
                    x, y, zz = map(float, parts[1:4])
                    out.append(f'vn {x:.7f} {-zz:.7f} {y:.7f}')
                elif parts[0] in ('vt', 'f'):
                    out.append(line)
            (root/(name+'.obj')).write_text('\n'.join(out)+'\n')
            manifest[name] = {'width': bounds[0][1]-bounds[0][0],
                              'depth': bounds[2][1]-bounds[2][0],
                              'height': bounds[1][1]-bounds[1][0]}
        (root/'colormap.png').write_bytes(z.read('Models/OBJ format/Textures/colormap.png'))
        (root/'LICENSE.txt').write_bytes(z.read('License.txt'))
    (root/'manifest.json').write_text(json.dumps(manifest, indent=2))
    (root/'SOURCE.md').write_text('# City models\n\nKenney City Kit Commercial 2.1, CC0.\n\n'
        'Official page: https://kenney.nl/assets/city-kit-commercial\n\n'
        'Only twelve OBJ models and their small palette texture are included. '
        'Vertices/normals were rotated from Y-up to Z-up; no geometry was invented. '
        'The assembled district, roads, landscaping and ground textures are generated by urban_scene.py.\n')
    print(f'Prepared {len(manifest)} models in {root}')


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--archive')
    prepare(parser.parse_args().archive)
